repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        language: system
        entry: make lint

      - id: typecheck
        name: typecheck
        language: system
        entry: make typecheck
