version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=${ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${SECRET_KEY}
    command: server /data
    volumes:
      - minio_data:/data 

volumes:
  minio_data:
    driver: local
